default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tcc_development

test:
  <<: *default
  database: tcc_test

production:
  <<: *default
  database: tcc_production
  username: tcc
  password: <%= ENV["TCC_DATABASE_PASSWORD"] %>
